# Do not change the amount of items in the lists or attempt to change what is tracked for each item in the lists
# Ex: Each material can be changed, but it will not change what is actually being tracked

# Placeholders:
# {current} - The current item's display name with its color codes
# {current-no-color} - The current item's display name as plaintext (no color codes)
# {previous} - The previous item's display name with its color codes
# {previous-no-color} - the previous item's display name as plaintext (no color codes)
# {price} - Price to unlock the current upgrade
# {amount} - Amount of current item the island has tracked
# {required} - Required amount of items to unlock the upgrade purchase
# {recipe} - Colorized farming recipe display name
# {data-type} - farming/slayer/mining/fishing
# {required-half} - Specific to farming, it is half the amount required for the upgrade
# {progress-indicator} - &f[&cx&f] or &f[&a✓& (If amount > required)

# Important: Placeholders cannot be used everywhere. In-line comments will show where placeholders are available
my-sql:
  host: null
  port: null
  database: null
  username: null
  password: null

# If a field says Nullable and you don't want to include it, just delete the value
events: # Dispatches sound + message + title to all members of the island
  island-progressed: # A new upgrade becomes purchasable
    sound: ENTITY_PLAYER_LEVELUP
    message: "&e[&6&l!&e] &7Island can now buy {current} &7upgrade!" # {data-type} {current} {current-no-color}
    title:
      title: "&6&l/is {data-type} &7Progressed!" # Nullable {data-type} {current} {current-no-color}
      subtitle: "{current} &7upgrade is now purchasable!" # Nullable {data-type} {current} {current-no-color}
      fade-in: 40 # Whole number of ticks
      persist: 100 # Whole number of ticks
      fade-out: 40 # Whole number of ticks
  island-upgraded: # An upgrade was purchased
    sound: UI_TOAST_CHALLENGE_COMPLETE
    message: "&e[&6&l!&e] &6&l/is {data-type}&7 upgraded! {current} &7unlocked!" # {data-type} {current} {current-no-color}
    title:
      title: "&6&l/is {data-type} &7Upgraded!" # Nullable {data-type} {current} {current-no-color}
      subtitle: "{current} &7has been unlocked!" # Nullable {data-type} {current} {current-no-color}
      fade-in: 40 # Whole number of ticks
      persist: 100 # Whole number of ticks
      fade-out: 40 # Whole number of ticks

# Everything below is GUI-related
all:
  filler:
    material: BLACK_STAINED_GLASS_PANE
  conditions-met:
    material: LIME_STAINED_GLASS_PANE # Item that will show when an upgrade is ready to be purchased
    display-name: "&7{current-no-color}" # {current} {current-no-color}
    lore:
      - "&7Spend &a${price} &7to unlock {current}" # {price} {current} {current-no-color}
  locked:
    display-name: "&7&l???" # Displays when it is locked and the previous is not unlocked
    display-name-unlockable: "&c&k{current-no-color}" # {current} {current-no-color} - Displays when it is locked and the previous IS unlocked.
    lore: # Displays when previous is not unlocked
      - "&7&l???"
      - ""
      - "&c&lLOCKED"
    material: RED_STAINED_GLASS_PANE # Item that will show in place of fully locked items
    material-unlockable: ORANGE_STAINED_GLASS_PANE # Item that will show on locked items that are able to have their unlock progress seen
    message: "&4&l[!]&c Island has not unlocked that!" # Message the player receives when placing a locked item
    sound: BLOCK_ANVIL_PLACE # Sound that will play when trying to place a locked item