# Do not change the amount of items in the lists or attempt to change what is tracked for each item in the lists
# Ex: Each material can be changed, but it will not change what is actually being tracked

# Placeholders:
# {current} - The current item's display name with its color codes
# {current-no-color} - The current item's display name as plaintext (no color codes)
# {previous} - The previous item's display name with its color codes
# {previous-no-color} - the previous item's display name as plaintext (no color codes)
# {price} - Price to unlock the current upgrade
# {amount} - Amount of current item the island has tracked
# {required} - Required amount of items to unlock the upgrade purchase
# {recipe} - Colorized farming recipe display name
# {data-type} - farming/slayer/mining/fishing
# {required-half} - Specific to farming, it is half the amount required for the upgrade
# {progress-indicator} - &f[&cx&f] or &f[&a✓& (If amount > required)

# Important: Placeholders cannot be used everywhere. In-line comments will show where placeholders are available
my-sql:
  host: null
  port: null
  database: null
  username: null
  password: null

island-levels-menu-title: "&x&0&8&4&c&f&bI&x&1&5&5&9&f&bs&x&2&1&6&6&f&bl&x&2&e&7&3&f&ba&x&3&b&7&f&f&cn&x&4&7&8&c&f&cd &x&5&4&9&9&f&cU&x&6&1&a&6&f&cp&x&6&e&b&3&f&cg&x&7&a&c&0&f&cr&x&8&7&c&c&f&da&x&9&4&d&9&f&dd&x&a&0&e&6&f&de&x&a&d&f&3&f&ds"
island-slayer-menu-title: "&x&0&5&a&f&c&6&lI&x&0&c&b&6&c&b&ls&x&1&4&b&d&d&0&ll&x&1&b&c&4&d&5&la&x&2&3&c&b&d&a&ln&x&2&a&d&2&d&f&ld &x&3&2&d&a&e&4&lS&x&3&9&e&1&e&9&ll&x&4&1&e&8&e&e&la&x&4&8&e&f&f&3&ly&x&5&0&f&6&f&8&le&x&5&7&f&d&f&d&lr"
island-farming-menu-title: "&x&0&5&a&f&c&6&lI&x&0&c&b&6&c&b&ls&x&1&4&b&d&d&0&ll&x&1&b&c&4&d&5&la&x&2&3&c&b&d&a&ln&x&2&a&d&2&d&f&ld &x&3&2&d&a&e&4&lF&x&3&9&e&1&e&9&la&x&4&1&e&8&e&e&lr&x&4&8&e&f&f&3&lm&x&5&0&f&6&f&8&li&x&5&7&f&d&f&d&ln&x&a&d&f&3&f&dg"
island-mining-menu-title: "&x&0&5&a&f&c&6&lI&x&0&c&b&6&c&b&ls&x&1&4&b&d&d&0&ll&x&1&b&c&4&d&5&la&x&2&3&c&b&d&a&ln&x&2&a&d&2&d&f&ld &x&3&2&d&a&e&4&lM&x&3&9&e&1&e&9&li&x&4&1&e&8&e&e&ln&x&4&8&e&f&f&3&li&x&5&0&f&6&f&8&ln&x&5&7&f&d&f&d&lg"
island-fishing-menu-title: "&x&0&5&a&f&c&6&lI&x&0&c&b&6&c&b&ls&x&1&4&b&d&d&0&ll&x&1&b&c&4&d&5&la&x&2&3&c&b&d&a&ln&x&2&a&d&2&d&f&ld &x&3&2&d&a&e&4&lF&x&3&9&e&1&e&9&li&x&4&1&e&8&e&e&ls&x&4&8&e&f&f&3&lh&x&5&0&f&6&f&8&li&x&5&7&f&d&f&d&ln&x&a&d&f&3&f&dg"

# If a field says Nullable and you don't want to include it, just delete the value
events: # Dispatches sound + message + title to all members of the island
  island-upgraded: # An upgrade was purchased
    sound: UI_TOAST_CHALLENGE_COMPLETE
    message: "&e[&6&l!&e] &6&l/is {data-type}&7 upgraded! {current} &7unlocked!" # {data-type} {current} {current-no-color}
    title:
      title: "&6&l/is {data-type} &7Upgraded!" # Nullable {data-type} {current} {current-no-color}
      subtitle: "{current} &7has been unlocked!" # Nullable {data-type} {current} {current-no-color}
      fade-in: 40 # Whole number of ticks
      persist: 100 # Whole number of ticks
      fade-out: 40 # Whole number of ticks

# Everything below is GUI-related
gui:
  filler:
    material: BLACK_STAINED_GLASS_PANE
  locked:
    display-name: "&7{name}"
    material: RED_STAINED_GLASS_PANE # Item that will show in place of locked items
    sound: BLOCK_ANVIL_PLACE # Sound that will play when trying to place a locked item
  unlocked:
    display-name: "&e&l{name}" #name
  slayer:
    locked:
      - '{progress-indicator} &7{amount}/{required} {previous} &7slain'
      - ''
      - '&c&lLOCKED'
    unlocked:
      - '&7{amount} {current-no-color} slain'
  farming:
    locked:
      - '{progress-indicator} &7{amount}/{required} {previous} &7Grown'
      - ''
      - '&7&lOR'
      - ''
      - '{progress-indicator-half} &7{amount-or-half-required}/{required-half} {previous}
        &7Grown'
      - '&7&lTHEN'
      - '&f{progress-indicator-recipe} {recipe}'
      - ''
      - '&c&lLOCKED'
    unlocked:
      - '&7{amount} {current-no-color} Grown'
  mining:
    unlocked: # {amount} {current} {current-no-color}
      - '&7{amount} {current-no-color} Nodes Mined'
    locked: # {amount} {required} {previous} {previous-no-color} {price}
      - '{progress-indicator} &7{amount}/{required} {previous} Nodes Mined'
      - ''
      - '&c&lLOCKED'
  fishing:
    unlocked: # {amount} {current} {current-no-color}
      - '&7{amount} {current-no-color} Caught'
    locked: # {amount} {required} {previous} {previous-no-color} {price}
      - '{progress-indicator} &7{amount}/{required} {previous} Caught'
      - ''
      - '&c&lLOCKED'
farming:
  recipe: # Config values for farming recipes
    display-name: '&eFarming Recipe &a(&e{current}&a)' # {current} is replaced with the non-colored name of the crop in title case (Beetroot, Sweet Berries, Cocoa Beans, etc.)
    lore: # {current} Same functionality as above
      - '&fRight click to claim'
      - '&e&l{current}&f Recipe'