# Do not change the amount of items in the lists or attempt to change what is tracked for each item in the lists
# Ex: Each material can be changed, but it will not change what is actually being tracked

# Placeholders:
# {current} - The current item's display name with its color codes
# {current-no-color} - The current item's display name as plaintext (no color codes)
# {previous} - The previous item's display name with its color codes
# {previous-no-color} - the previous item's display name as plaintext (no color codes)
# {price} - Price to unlock the current upgrade
# {amount} - Amount of current item the island has tracked
# {required} - Required amount of items to unlock the upgrade purchase
# {recipe} - Colorized farming recipe display name

# Important: Placeholders cannot be used everywhere. In-line comments will show where placeholders are available
all:
  filler:
    material: BLACK_STAINED_GLASS_PANE
  conditions-met:
    material: LIME_STAINED_GLASS_PANE # Item that will show when an upgrade is ready to be purchased
    display-name: "&7{current-no-color}" # {current} {current-no-color}
    lore:
      - "&a&lSpend {price} to purchase upgrade!" # {price}
  locked:
    display-name: "&7&l???" # Displays when it is locked and the previous is not unlocked
    display-name-unlockable: "&7{current}" # {current} {current-no-color} - Displays when it is locked and the previous IS unlocked.
    lore: # Displays when previous is not unlocked
      - "&7&l???"
      - ""
      - "&c&lLOCKED"
    material: RED_STAINED_GLASS_PANE # Item that will show in place of fully locked items
    material-unlockable: ORANGE_STAINED_GLASS_PANE # Item that will show on locked items that are able to have their unlock progress seen
    message: "&4&l[!]&c Island has not unlocked that!" # Message the player receives when placing a locked item
    sound: BLOCK_ANVIL_PLACE # Sound that will play when trying to place a locked item
mining:
  lore:
    unlocked: # {amount} {current} {current-no-color}
      - "&7{amount} {current} Node&7 mined"
    locked: # {amount} {required} {previous} {previous-no-color}
      - "&7{amount}/{required} {previous} Node &7mined"
  cobblestone:
    material: COBBLESTONE # Item that will show when unlocked
    display-name: "&6&lCobblestone"
  coal:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: COAL_ORE # Item that will show when unlocked
    display-name: "&6&lCoal"
  copper:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: COPPER_ORE # Item that will show when unlocked
    display-name: "&6&lCopper"
  nether-gold:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: NETHER_GOLD_ORE # Item that will show when unlocked
    display-name: "&6&lNether Gold"
  nether-quartz:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: NETHER_QUARTZ_ORE # Item that will show when unlocked
    display-name: "&6&lNether Quartz"
  iron:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: IRON_ORE # Item that will show when unlocked
    display-name: "&6&lIron"
  ruby:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: REDSTONE_ORE # Item that will show when unlocked
    display-name: "&6&lRuby"
  lapis:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: LAPIS_ORE # Item that will show when unlocked
    display-name: "&6&lLapis"
  diamond:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: DIAMOND_ORE # Item that will show when unlocked
    display-name: "&6&lDiamond"
  emerald:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: EMERALD_ORE # Item that will show when unlocked
    display-name: "&6&lEmerald"
  ancient-debris:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: ANCIENT_DEBRIS # Item that will show when unlocked
    display-name: "&6&lAncient Debris"
slayer:
  lore:
    unlocked: # {amount} {current} {current-no-color}
      - "&7{amount} &e&l{current} &7slain"
    locked: # {amount} {required} {previous} {previous-no-color}
      - "&7{amount}/{required} &e&l{previous} &7slain"
  rabbit:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 57519 # ID of the head that will show when unlocked
    display-name: "&e&lRabbit"
  chicken:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 53916 # ID of the head that will show when unlocked
    display-name: "&e&lChicken"
  sheep:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 57345 # ID of the head that will show when unlocked
    display-name: "&e&lSheep"
  pig:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 55184 # ID of the head that will show when unlocked
    display-name: "&e&lPig"
  cow:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 49706 # ID of the head that will show when unlocked
    display-name: "&e&lCow"
  zombie:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 4187 # ID of the head that will show when unlocked
    display-name: "&e&lZombie"
  spider:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 26010 # ID of the head that will show when unlocked
    display-name: "&e&lSpider"
  creeper:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 4169 # ID of the head that will show when unlocked
    display-name: "&e&lCreeper"
  skeleton:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 4005 # ID of the head that will show when unlocked
    display-name: "&e&lSkeleton"
  slime:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 22210 # ID of the head that will show when unlocked
    display-name: "&e&lSlime"
  guardian:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 25292 # ID of the head that will show when unlocked
    display-name: "&e&lGuardian"
  enderman:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 38106 # ID of the head that will show when unlocked
    display-name: "&e&lEnderman"
  magma-cube:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 323 # ID of the head that will show when unlocked
    display-name: "&e&lMagma Cube"
  blaze:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 47778 # ID of the head that will show when unlocked
    display-name: "&e&lBlaze"
  ghast:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 40638 # ID of the head that will show when unlocked
    display-name: "&e&lGhast"
  wither-skeleton:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 22400 # ID of the head that will show when unlocked
    display-name: "&e&lWither Skeleton"
  iron-golem:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    head-id: 341 # ID of the head that will show when unlocked
    display-name: "&e&lIron Golem"
farming:
  recipe: # Config values for farming recipes
    display-name: "&eFarming Recipe &a(&e{current}&a)" # {current} is replaced with the non-colored name of the crop in title case (Beetroot, Sweet Berries, Cocoa Beans, etc.)
    lore: # {current} Same functionality as above
      - "&fBypasses the conditions for an island's"
      - "&e&l{current}&f upgrade"
  lore:
    unlocked:
      - "&7{amount} {current}&7 Grown" # {amount} {current} {current-no-color}
    locked: # {amount} {required} {previous} {previous-no-color} {recipe}
      - "&7{amount}/{required} {previous} &7Grown"
      - ""
      - "&7&lOR"
      - ""
      - "&f[&cx&f] {recipe}&f used"
  wheat:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: WHEAT # Item that will show when unlocked
    display-name: "&e&lWheat"
  beetroot:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: BEETROOT # Item that will show when unlocked
    display-name: "&e&lBeetroot"
  carrot:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: CARROT # Item that will show when unlocked
    display-name: "&e&lCarrot"
  potato:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: POTATO # Item that will show when unlocked
    display-name: "&e&lPotato"
  sugar-cane:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: SUGAR_CANE # Item that will show when unlocked
    display-name: "&e&lSugar Cane"
  kelp:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: KELP # Item that will show when unlocked
    display-name: "&e&lKelp"
  nether-wart:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: NETHER_WART # Item that will show when unlocked
    display-name: "&e&lNether Wart"
  sweet-berries:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: SWEET_BERRIES # Item that will show when unlocked
    display-name: "&e&lSweet Berries"
  bamboo:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: BAMBOO # Item that will show when unlocked
    display-name: "&e&lBamboo"
  chorus-flower:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: CHORUS_FLOWER # Item that will show when unlocked
    display-name: "&e&lChorus Flower"
  cactus:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: CACTUS # Item that will show when unlocked
    display-name: "&e&lCactus"
  melon:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: MELON # Item that will show when unlocked
    display-name: "&e&lMelon"
  pumpkin:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: PUMPKIN # Item that will show when unlocked
    display-name: "&e&lPumpkin"
  cocoa-beans:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade
    material: COCOA_BEANS # Item that will show when unlocked
    display-name: "&e&lCocoa Beans"
fishing: