# {amount} = However many of the current thing their island has tracked so far
# {progress} = However many of the requirement their island has tracked so far
# Ex: Lore: {progress}/150,000 Zombies slain or {progress}/200 Coal nodes mined
# Do not change the amount of items in the lists or attempt to change what is tracked for each item in the lists
# Ex: Each material can be changed, but it will not change what is actually being tracked
all:
  filler:
    material: BLACK_STAINED_GLASS_PANE
  conditions-met:
    material: ORANGE_STAINED_GLASS_PANE # Item that will show when an upgrade is ready to be purchased
    display-name: "&7&l???"
    lore:
      - "&a&lSpend {price} to purchase upgrade!" # {price} will translate to the price of the upgrade
  locked:
    display-name: "&7&l???" # Displays when it is locked and the previous is not unlocked
    display-name-unlockable: "{current}" # Displays when it is locked and the previous IS unlocked. {current} will be replaced with its display name
    lore: # Displays when previous is not unlocked
      - "&7&l???"
    material: RED_STAINED_GLASS_PANE # Item that will show in place of locked items
    message: "&4&l[!]&c Island has not unlocked that!" # Message the player receives when placing a locked item
    sound: BLOCK_ANVIL_PLACE # Sound that will play when trying to place a locked item
mining:
  lore:
    unlocked:
      - "&7{amount} {current} mined"  # {amount} replaced with current tracked amount. {current} replaced with display-name.
    locked:
      - "&7{amount}/{required} {previous} mined" # {required} replaced with required amount to unlock. {previous} replaced with previous upgrade's display-name
  cobblestone:
    material: COBBLESTONE # Item that will show in /is mining
    display-name: "&7Cobblestone Nodes"
  coal:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: COAL_ORE
    display-name: "&7Coal Nodes"
  copper:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: COPPER_ORE
    display-name: "&7Copper Nodes"
  nethergold:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: NETHER_GOLD_ORE
    display-name: "&7Nether Gold Nodes"
  netherquartz:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: NETHER_QUARTZ_ORE
    display-name: "&7Nether Quartz Nodes"
  iron:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: IRON_ORE
    display-name: "&7Iron Nodes"
  ruby:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: REDSTONE_ORE
    display-name: "&7Ruby Nodes"
  lapis:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: LAPIS_ORE
    display-name: "&7Lapis Nodes"
  diamond:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: DIAMOND_ORE
    display-name: "&7Diamond Nodes"
  emerald:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: EMERALD_ORE
    display-name: "&7Emerald Nodes"
  ancientdebris:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: ANCIENT_DEBRIS
    display-name: "&7Ancient Debris Nodes"
slayer:
  rabbit:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 57519 # ID of the head that will show in /is slayer
    display-name: "&7Rabbit"
  chicken:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 53916
    display-name: "&7Chicken"
  sheep:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 57345
    display-name: "&7Sheep"
  pig:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 55184
    display-name: "&7Pigs"
  cow:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 49706
    display-name: "&7Cows"
  zombie:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 4187
    display-name: "&7Zombies"
  spider:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 26010
    display-name: "&7Spiders"
  creeper:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 4169
    display-name: "&7Creepers"
  skeleton:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 4005
    display-name: "&7Skeletons"
  slime:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 22210
    display-name: "&7Slimes"
  guardian:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 25292
    display-name: "&7Guardians"
  enderman:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 38106
    display-name: "&7Endermen"
  magma-cube:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 323
    display-name: "&7Magma Cubes"
  blaze:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 47778
    display-name: "&7Blazes"
  ghast:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 40638
    display-name: "&7Ghasts"
  wither-skeleton:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 22400
    display-name: "&7Wither Skeletons"
  iron-golem:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    head-id: 341
    display-name: "&7Iron Golem"
farming:
  lore:
    unlocked:
      - "&7{amount} Beetroot harvested"
    locked:
      - "&7{progress}/1000 Wheat harvested"
      - "&7&lOR"
      - "&7[x] Beetroot Recipe Used"
  wheat:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: WHEAT
    display-name: "&7Wheat"
  beetroot:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: BEETROOT
    display-name: "&7Beetroot"
  carrot:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: CARROT
    display-name: "&7Carrots"
  potato:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: POTATO
    display-name: "&7Potatoes"
  sugar-cane:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: SUGAR_CANE
    display-name: "&7Sugar Cane"
  kelp:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: KELP
    display-name: "&7Kelp"
  nether-wart:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: NETHER_WART
    display-name: "&7Nether Warts"
  sweet-berries:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: SWEET_BERRIES
    display-name: "&7Sweet Berries"
  bamboo:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: BAMBOO
    display-name: "&7Bamboo"
  chorus-flower:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: CHORUS_FLOWER
    display-name: "&7Chorus Flower"
  cactus:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: CACTUS
    display-name: "&7Cactus"
  melon:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: MELON
    display-name: "&7Melon"
  pumpkin:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: PUMPKIN
    display-name: "&7Pumpkin"
  cocoa:
    amount: 10 # Amount of previous required to unlock
    price: 1000 # Price of upgrade once amount is met
    material: COCOA_BEANS
    display-name: "&7Cocoa Beans"
fishing: