# {amount} = However many of the current thing their island has tracked so far
# {progress} = However many of the requirement their island has tracked so far
# Ex: Lore: {progress}/150,000 Zombies slain or {progress}/200 Coal nodes mined
# Do not change the amount of items in the lists or attempt to change what is tracked for each item in the lists
# Ex: Each material can be changed, but it will not change what is actually being tracked
all:
  filler:
    material: BLACK_STAINED_GLASS_PANE
  locked:
    material: ORANGE_STAINED_GLASS_PANE # Item that will show in place of locked items
mining:
  '1':
    material: COBBLESTONE # Item that will show in /is mining
    display-name: "&7Cobblestone Nodes"
    lore:
      unlocked:
        - "&7{amount} Cobblestone Nodes Mined"
  '2':
    material: COAL_ORE
    display-name: "&7Coal Nodes"
    lore:
      locked:
        - "&c{progress}/50 Cobblestone Nodes mined"
      unlocked:
        - "&7{amount} Coal Nodes Mined"
  '3':
    material: COPPER_ORE
    display-name: "&7Copper Nodes"
    lore:
      locked:
        - "&c{progress}/50 Coal Nodes mined"
      unlocked:
        - "&7{amount} Copper Nodes Mined"
  '4':
    material: NETHER_GOLD_ORE
    display-name: "&7Nether Gold Nodes"
    lore:
      locked:
        - "&c{progress}/50 Copper Nodes mined"
      unlocked:
        - "&7{amount} Nether Gold Nodes Mined"
  '5':
    material: NETHER_QUARTZ_ORE
    display-name: "&7Nether Quartz Nodes"
    lore:
      locked:
        - "&c{progress}/50 Nether Gold Nodes mined"
      unlocked:
        - "&7{amount} Nether Quartz Nodes Mined"
  '6':
    material: IRON_ORE
    display-name: "&7Iron Nodes"
    lore:
      locked:
        - "&c{progress}/50 Nether Quartz Nodes mined"
      unlocked:
        - "&7{amount} Iron Nodes Mined"
  '7':
    material: REDSTONE_ORE
    display-name: "&7Ruby Nodes"
    lore:
      locked:
        - "&c{progress}/50 Iron Nodes mined"
      unlocked:
        - "&7{amount} Ruby Nodes Mined"
  '8':
    material: LAPIS_ORE
    display-name: "&7Lapis Nodes"
    lore:
      locked:
        - "&c{progress}/50 Ruby Nodes mined"
      unlocked:
        - "&7{amount} Lapis Nodes Mined"
  '9':
    material: DIAMOND_ORE
    display-name: "&7Diamond Nodes"
    lore:
      locked:
        - "&c{progress}/50 Lapis Nodes mined"
      unlocked:
        - "&7{amount} Diamond Nodes Mined"
  '10':
    material: EMERALD_ORE
    display-name: "&7Emerald Nodes"
    lore:
      locked:
        - "&c{progress}/50 Diamond Nodes mined"
      unlocked:
        - "&7{amount} Emerald Nodes Mined"
  '11':
    material: ANCIENT_DEBRIS
    display-name: "&7Ancient Debris Nodes"
    lore:
      locked:
        - "&c{progress}/50 Emerald Nodes mined"
      unlocked:
        - "&7{amount} Ancient Debris Nodes Mined"
slayer:
  '1':
    head-id: 57519 # ID of the head that will show in /is slayer
    display-name: "&7Rabbit"
    lore:
      unlocked:
        - "&7{amount} Rabbit slain"
  '2':
    head-id: 53916
    display-name: "&7Chicken"
    lore:
      unlocked:
        - "&7{amount} Chicken slain"
  '3':
    head-id: 57345
    display-name: "&7Sheep"
    lore:
      unlocked:
        - "&7{amount} Sheep slain"
  '4':
    head-id: 55184
    display-name: "&7Pigs"
    lore:
      unlocked:
        - "&7{amount} Pigs slain"
  '5':
    head-id: 49706
    display-name: "&7Cows"
    lore:
      unlocked:
        - "&7{amount} Cows slain"
  '6':
    head-id: 4187
    display-name: "&7Zombies"
    lore:
      unlocked:
        - "&7{amount} Zombies slain"
  '7':
    head-id: 26010
    display-name: "&7Spiders"
    lore:
      unlocked:
        - "&7{amount} Spiders slain"
  '8':
    head-id: 4169
    display-name: "&7Creepers"
    lore:
      unlocked:
        - "&7{amount} Creepers slain"
  '9':
    head-id: 4005
    display-name: "&7Skeletons"
    lore:
      unlocked:
        - "&7{amount} Skeletons slain"
  '10':
    head-id: 22210
    display-name: "&7Slimes"
    lore:
      unlocked:
        - "&7{amount} Slimes slain"
  '11':
    head-id: 25292
    display-name: "&7Guardians"
    lore:
      unlocked:
        - "&7{amount} Guardians slain"
  '12':
    head-id: 38106
    display-name: "&7Endermen"
    lore:
      unlocked:
        - "&7{amount} Endermen slain"
  '13':
    head-id: 323
    display-name: "&7Magma Cubes"
    lore:
      unlocked:
        - "&7{amount} Magma Cubes slain"
  '14':
    head-id: 47778
    display-name: "&7Blazes"
    lore:
      unlocked:
        - "&7{amount} Blazes slain"
  '15':
    head-id: 40638
    display-name: "&7Ghasts"
    lore:
      unlocked:
        - "&7{amount} Ghasts slain"
  '16':
    head-id: 22400
    display-name: "&7Wither Skeletons"
    lore:
      unlocked:
        - "&7{amount} Wither Skeletons slain"
  '17':
    head-id: 341
    display-name: "&7Iron Golems"
    lore:
      unlocked:
        - "&7{amount} Iron Golems slain"
farming:
  '1':
  '2':
  '3':
  '4':
  '5':
  '6':
  '7':
  '8':
  '9':
  '10':
  '11':
  '12':
  '13':
  '14':
fishing: