name: HSProgression
author: Daniel Ohrin
version: '${project.version}'
main: net.highskiesmc.progression.HSProgression
api-version: 1.19
depend: [HSNodes, HSFishing, Vault, RoseStacker, ItemsAdder]
commands:
  hsprogression:
    aliases:
      - hsp