name: HSProgression
author: Daniel Ohrin
version: '${project.version}'
main: net.highskiesmc.progression.HSProgression
api-version: 1.19
softdepend:
  - WildStacker
depend:
  - HSNodes
commands:
  hsprogression:
    aliases:
      - hsp