name: HSProgression
author: Daniel Ohrin
version: '${project.version}'
main: net.highskiesmc.hsprogression.HSProgression
api-version: 1.13
depend: [ SuperiorSkyblock2, RoseStacker, Vault, HeadDatabase, HSNodes, ItemsAdder, HSFishing, Vault ]
commands:
  hsprogression:
    aliases:
      - hsp